name: CD

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        run: |
          docker build . --tag ghcr.io/vincent-thomas/tdrive:latest
          docker push ghcr.io/vincent-thomas/tdrive:latest
