name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - uses: actions/cache@v3
        name: Cacha nextjs mapp
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: pnpm install
      - run: pnpm p:gen
        name: Generera prisma
      - run: SKIP_ENV_VALIDATION=1 pnpm build
  deploy-preview:
    runs-on: ubuntu-latest
    environment:
      name: Testning
      url: ${{ steps.vercel-preview-deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - uses: amondnet/vercel-action@v20
        id: vercel-preview-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          github-comment: false
          zeit-token: ${{secrets.VERCEL_TOKEN}}
